version: '3.8'
services:
  dev-db:
    image: postgres:15.3-alpine
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: roundest-mon

volumes:
  postgres-data:
