import { type NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'

import { api, getOptionsForVote } from '~/utils'

const Home: NextPage = () => {
  const [ids, updateIds] = useState(() => getOptionsForVote())
  const [first, second] = ids
  const firstPokemon = api.pokemon.getPokemonById.useQuery({ id: first })
  const secondPokemon = api.pokemon.getPokemonById.useQuery({ id: second })

  if (firstPokemon.isLoading || secondPokemon.isLoading) return null
  const firstPokemonImg =
    (firstPokemon?.data && firstPokemon.data.sprites.other?.['official-artwork'].front_default) ||
    ''
  const secondPokemonImg =
    (secondPokemon?.data && secondPokemon.data.sprites.other?.['official-artwork'].front_default) ||
    ''

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='h-screen w-screen flex flex-col justify-center items-center bg-zinc-800 text-zinc-100'>
        <section className='p-8'>
          <h1 className='text-2xl text-center'>Which Pokémon is Rounder?</h1>
        </section>
        <section className='border rounded p-8 flex items-center justify-between gap-8 max-w-2xl'>
          <div className='h-64 w-64 bg-transparent flex flex-col items-center justify-center'>
            <img className='w-full' src={firstPokemonImg} alt={firstPokemon.data.name} />
            <p className='capitalize text-lg font-bold'>{firstPokemon.data.name}</p>
          </div>
          <div>VS</div>
          <div className='h-64 w-64 bg-transparent flex flex-col items-center justify-center'>
            <img src={secondPokemonImg} alt={secondPokemon.data.name} />
            <p className='capitalize text-lg font-bold'>{secondPokemon.data.name}</p>
          </div>
        </section>
      </main>
    </>
  )
}

export default Home
